import GqlApi from "../lib/gql-api";
import {ISPFRouteResponse} from "../lib/spf-route-response";
import {IUserData} from "../lib/jwt";
import {fetchCourseListForView} from "./courses";

export async function viewMarketing(client: GqlApi, user: IUserData, locale: string) : Promise<ISPFRouteResponse> {
    // const relevant = await fetchCourseListForView(client, 'relevant');
    // console.log('RELEVANT COURSES', relevant)
    const relevant = [ { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Java Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-intro-to-python.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Java Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Java Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Python Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Java Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Python Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'JS Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'Java Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false },
    { id: 'Q291cnNlOmJhc2ljc19qYXZh',
    title: 'JS Basics',
    headline: 'Learn basic Java programming with EXLskills!',
    enrolled_count: 0,
    view_count: 0,
    logo_url: 'https://s3-us-west-2.amazonaws.com/exlskills-course-logos/course-java-basics.jpg',
    skill_level: 1,
    est_minutes: 1080,
    primary_topic: 'Java',
    verified_cert_cost: 30,
    delivery_methods: [],
    url_id: 'java-basics-basics_java',
    badge_url: 'https://s3-us-west-2.amazonaws.com/exlskills-topic-badges/java.png',
    skill_level_text: 'Beginner',
    est_minutes_text: '18 Hour(s)',
    has_live_mode: false } ];
    return {
        contentTmpl: 'marketing-index',
        layout: 'marketing',
        meta: {
            title: 'EXLskills',
            description: 'Learn high-paying tech skills for free'
        },
        data: {
            courses: {
                relevant
            },
            marketing: [
              { title: "Free & Open-source content from Github",
                subtitle: "100% of our content is free and open-source (hosted on Github)",
                image: "https://s3-us-west-2.amazonaws.com/exlskills-mktg-assets/site-assets/_index/ico-color-opensource.svg"
              },
              { title: "Guided, intelligent process with chatbot help",
                subtitle: "Intelligent IDE (via EXLcode) fixes mistakes in your code and helps you learn by doing",
                image: "https://s3-us-west-2.amazonaws.com/exlskills-mktg-assets/site-assets/_index/ico-color-guided.svg"
              },
              { title: "Expert help instantly",
                subtitle: "Need help? Ask an expert instantly and receive one-on-one help",
                image: "https://s3-us-west-2.amazonaws.com/exlskills-mktg-assets/site-assets/_index/ico-color-validated.svg"
              },
            ]
        }
    }
}
